package empirical

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/revelara-ai/orion/internal/orchestrator/spec"
	"github.com/revelara-ai/orion/internal/proof/proofexec"
	"github.com/revelara-ai/orion/internal/proof/testsynth"
	"github.com/revelara-ai/orion/internal/proof/truthalign"
)

// pyTool is Python's empirical surface (or-4y7.9, library tracer): staging is
// the shared tree copy; the unit channel synthesizes a python driver
// (case:segment dispatch, mirroring the Go driver's restart-boundary protocol)
// and runs each segment as a fresh sandboxed interpreter process — a real
// process boundary, so restart steps prove persistence exactly like Go. The
// http/exec channels refuse loudly: the tracer proves libraries; a runnable
// python service (argv-shaped, not a compiled binary) is the next
// generalization, and pretending with a stub would be a meaningless probe.
type pyTool struct{}

func (pyTool) Language() string { return "python" }

func (pyTool) Stage(src, dst string) error { return pyStage(src, dst) }

// pyStage copies the python artifact tree into the proof-controlled dir:
// production *.py (and asset files), excluding bytecode caches, dot-dirs, and
// any prior harness-authored corpus/driver (orion_*). The shared stageArtifact
// is Go-shaped (it requires buildable .go sources), so python stages its own.
func pyStage(src, dst string) error {
	staged := 0
	err := filepath.WalkDir(src, func(p string, d os.DirEntry, werr error) error {
		if werr != nil {
			return werr
		}
		rel, rerr := filepath.Rel(src, p)
		if rerr != nil {
			return rerr
		}
		if rel == "." {
			return nil
		}
		name := d.Name()
		if d.IsDir() {
			if strings.HasPrefix(name, ".") || name == "__pycache__" {
				return filepath.SkipDir
			}
			return os.MkdirAll(filepath.Join(dst, rel), 0o755)
		}
		if strings.HasPrefix(name, "orion_") || strings.HasSuffix(name, ".pyc") {
			return nil
		}
		data, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		if strings.HasSuffix(name, ".py") {
			staged++
		}
		return os.WriteFile(filepath.Join(dst, rel), data, 0o644)
	})
	if err != nil {
		return err
	}
	if staged == 0 {
		return fmt.Errorf("no python sources in %s", src)
	}
	return nil
}

func (pyTool) Build(context.Context, string) (string, string, int, error) {
	return "", "", -1, fmt.Errorf("python empirical: http/exec probes are not supported yet (the library tracer proves unit and file cases); declare unit obligations")
}

// pyDriverIdentRE guards module names interpolated into the generated driver.
var pyDriverIdentRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$`)

func (pyTool) BuildUnitDriver(_ context.Context, binDir string, unitCases []spec.BehavioralCase) (string, bool, string, error) {
	var b strings.Builder
	b.WriteString("# Code generated by Orion proof/test-synthesis. DO NOT EDIT.\nimport importlib\nimport re\nimport sys\n\n\ndef fail(msg):\n    print(msg, file=sys.stderr)\n    sys.exit(1)\n\n\ndef run(key):\n")
	wrote := false
	for _, cs := range unitCases {
		if cs.Kind != spec.KindUnit || cs.Unit == nil {
			continue
		}
		mod := strings.TrimSpace(cs.Unit.Pkg)
		if mod == "" {
			fmt.Fprintf(&b, "    if key == %q:\n        fail(%q)\n", cs.ID+":0",
				"unit case "+cs.ID+" declares no importable module (pkg) — name the package the case calls")
			wrote = true
			continue
		}
		if !pyDriverIdentRE.MatchString(mod) {
			return "", false, fmt.Sprintf("unit case %s: pkg %q is not an importable module name", cs.ID, cs.Unit.Pkg), nil
		}
		seg := 0
		emitHead := func() {
			fmt.Fprintf(&b, "    if key == %q:\n", fmt.Sprintf("%s:%d", cs.ID, seg))
			fmt.Fprintf(&b, "        m = importlib.import_module(%q)\n        env = dict(vars(m))\n", mod)
		}
		emitHead()
		for i, st := range cs.Unit.Steps {
			if st.Restart {
				b.WriteString("        return\n")
				seg++
				emitHead()
			}
			if st.WantErrRE != "" {
				fmt.Fprintf(&b, "        try:\n            eval(compile(%q, '<case>', 'eval'), env)\n", st.Call)
				fmt.Fprintf(&b, "        except Exception as e:\n")
				fmt.Fprintf(&b, "            if not re.search(%q, str(e)):\n                fail('step %d: error %%r does not match %%r' %% (str(e), %q))\n", st.WantErrRE, i+1, st.WantErrRE)
				fmt.Fprintf(&b, "        else:\n            fail('step %d: the call was required to raise')\n", i+1)
			} else {
				fmt.Fprintf(&b, "        got = eval(compile(%q, '<case>', 'eval'), env)\n", st.Call)
				fmt.Fprintf(&b, "        want = eval(compile(%q, '<want>', 'eval'), {})\n", st.Want)
				fmt.Fprintf(&b, "        if got != want:\n            fail('step %d: got %%r, want %%r' %% (got, want))\n", i+1)
			}
		}
		b.WriteString("        return\n")
		wrote = true
	}
	if !wrote {
		return "", false, "no unit cases", nil
	}
	b.WriteString("    print('unknown case/segment', file=sys.stderr)\n    sys.exit(2)\n\n\nif __name__ == '__main__':\n    if len(sys.argv) != 3:\n        print('usage: driver <caseID> <segment>', file=sys.stderr)\n        sys.exit(2)\n    run(sys.argv[1] + ':' + sys.argv[2])\n")
	p := filepath.Join(binDir, "orion_unit_driver.py")
	if err := os.WriteFile(p, []byte(b.String()), 0o644); err != nil {
		return "", false, "", err
	}
	return p, true, "", nil
}

func (pyTool) UnitRound(ctx context.Context, driver string, unitCases []spec.BehavioralCase) (map[string]truthalign.ObligationStatus, string) {
	obs := map[string]truthalign.ObligationStatus{}
	var fails []string
	dir := filepath.Dir(driver)
	base := filepath.Base(driver)
	for _, cs := range unitCases {
		if cs.Kind != spec.KindUnit || cs.Unit == nil {
			continue
		}
		pass, detail := true, ""
		for seg := 0; seg < testsynth.UnitSegments(cs); seg++ {
			stdout, stderr, code, err := proofexec.RunTool(ctx, dir, "python", "python3", base, cs.ID, fmt.Sprint(seg))
			if err != nil {
				pass, detail = false, fmt.Sprintf("segment %d: %v", seg, err)
				break
			}
			if code != 0 {
				pass, detail = false, fmt.Sprintf("segment %d: %s", seg, strings.TrimSpace(stdout+stderr))
				break
			}
		}
		obs[cs.ID] = truthalign.ObligationStatus{Executed: true, Passed: pass}
		if !pass {
			fails = append(fails, cs.ID+": "+detail)
		}
	}
	return obs, strings.Join(fails, "; ")
}

func init() { registerLangTool(pyTool{}) }
