// Package testsynth authors behavioral tests FROM the spec — in the PROOF domain
// (or-60u, Trust invariant 1). The behavioral corpus is harness-owned and never
// authored by, or readable to, a generating agent. For the V2.0 Go HTTP
// time-service path, the corpus asserts the ResponseContract against the contract
// handler `handleTime` (a stable symbol of the generation contract).
//
// When the contract carries behavioral Cases, the corpus emits ONE test per case
// that issues the case's request and asserts its expectations, bracketed by
// ORION_OBLIGATION_RUN/PASS:<caseID> markers so the proof harness can record
// per-case executed/passed (a never-run case is a coverage hole, distinct from a
// failed one). With no Cases it falls back to the legacy single-assertion corpus,
// byte-identical for every existing caller.
//
// Manifesto: passing tests are not evidence of correctness unless the tests
// themselves come from the spec, independent of the code under test.
package testsynth

import (
	"fmt"
	"net/url"
	"sort"
	"strings"

	"github.com/revelara-ai/orion/internal/orchestrator/spec"
)

// Contract is the slice of the spec the behavioral corpus is synthesized from.
type Contract struct {
	Route    string
	Format   string // "json" | "text"
	TimeZone string
	// RequiredJSONKey is the legacy single-key seam: when set, the JSON response must
	// contain this key. Empty means "no specific key required" — it no longer defaults
	// to "time" (that imposed the time domain on every JSON probe). The real flow is
	// Cases-driven; this single-key path is for direct/legacy callers only.
	RequiredJSONKey string
	// Cases, when present, drives per-case obligation generation (the requirements
	// model). Empty → the legacy single-assertion corpus (behavioral always has the
	// default case, so this fires only for direct callers).
	Cases []spec.BehavioralCase
	// EntrySymbol is the DECLARED behavioral entry point the corpus invokes in-process
	// (the proof harness calls it directly). Empty defaults to DefaultEntrySymbol
	// ("handleTime", the HTTP-family contract symbol). Declaring it lets non-HTTP or
	// multi-route programs name their own handler instead of the hardwired symbol
	// (or-ciq, generalization item #9).
	EntrySymbol string
}

// DefaultEntrySymbol is the HTTP-family behavioral entry point used when a Contract
// does not declare its own (keeps the existing single-route HTTP path unchanged).
const DefaultEntrySymbol = "handleTime"

// Entry returns the declared behavioral entry symbol, defaulting to
// DefaultEntrySymbol. The corpus and the mutation target both call THIS symbol.
func (c Contract) Entry() string {
	if c.EntrySymbol == "" {
		return DefaultEntrySymbol
	}
	return c.EntrySymbol
}

// JSONKey returns the required JSON key and whether its value must be RFC3339. An
// unset key means "no specific key" (no time default).
func (c Contract) JSONKey() (key string, rfc3339 bool) {
	return c.RequiredJSONKey, false
}

// SynthesizeBehavioral returns Go test source (a corpus file) asserting the
// ResponseContract. It is written by the proof domain, compiled with the artifact,
// and run independently.
func SynthesizeBehavioral(c Contract) string {
	if len(c.Cases) == 0 {
		return legacyCorpus(c)
	}
	cases := append([]spec.BehavioralCase(nil), c.Cases...)
	sort.Slice(cases, func(i, j int) bool { return cases[i].ID < cases[j].ID })
	var b strings.Builder
	b.WriteString(`// Code generated by Orion proof/test-synthesis. DO NOT EDIT.
package main

import (
	"encoding/json"
	"fmt"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

var (
	_ = json.Unmarshal
	_ = strings.Contains
	_ = time.Parse
	_ = fmt.Println
	_ = httptest.NewRecorder
)
`)
	hasExec := false
	for _, cs := range cases {
		switch cs.Kind {
		case spec.KindExec:
			hasExec = true
			b.WriteString(execCaseTest(cs))
		case spec.KindFile:
			b.WriteString(fileCaseTest(cs))
		case spec.KindUnit:
			// unit cases live in their packages (SynthesizeUnitTests), not the root corpus
		default:
			b.WriteString(caseTest(cs, c.Entry()))
		}
	}
	out := b.String()
	if hasExec {
		// Exec cases need extra stdlib imports; injected as a second import block
		// after the header so the http emission stays byte-identical when no
		// exec case is present (golden-pinned).
		i := strings.Index(out, ")\n")
		out = out[:i+2] + execImports + out[i+2:]
	}
	return out
}

// caseTest emits one obligation test for a behavioral case (in-process via the
// handleTime contract symbol), bracketed by RUN/PASS markers.
func caseTest(cs spec.BehavioralCase, entry string) string {
	method := cs.Request.Method
	if method == "" {
		method = "GET"
	}
	target := cs.Request.Path + queryString(cs.Request.Query)
	var b strings.Builder
	fmt.Fprintf(&b, "\nfunc Test_obl_%s(t *testing.T) {\n", sanitize(cs.ID))
	fmt.Fprintf(&b, "\tfmt.Println(%q)\n", "ORION_OBLIGATION_RUN:"+cs.ID)
	if cs.Request.Body != "" {
		fmt.Fprintf(&b, "\treq := httptest.NewRequest(%q, %q, strings.NewReader(%q))\n", method, target, cs.Request.Body)
	} else {
		fmt.Fprintf(&b, "\treq := httptest.NewRequest(%q, %q, nil)\n", method, target)
	}
	for k, v := range cs.Request.Headers {
		fmt.Fprintf(&b, "\treq.Header.Set(%q, %q)\n", k, v)
	}
	fmt.Fprintf(&b, "\tw := httptest.NewRecorder()\n\t%s(w, req)\n", entry)
	fmt.Fprintf(&b, "\tif w.Code != %d {\n\t\tt.Fatalf(\"status = %%d, want %d\", w.Code)\n\t}\n", cs.Expect.Status, cs.Expect.Status)
	if cs.Expect.ContentType != "" {
		fmt.Fprintf(&b, "\tif ct := w.Header().Get(\"Content-Type\"); !strings.Contains(ct, %q) {\n\t\tt.Fatalf(\"content-type = %%q, want %s\", ct)\n\t}\n", cs.Expect.ContentType, cs.Expect.ContentType)
	}
	b.WriteString(assertionsSrc(cs.Expect.Assertions, "w.Body.Bytes()", "w.Body.String()"))
	fmt.Fprintf(&b, "\tfmt.Println(%q)\n}\n", "ORION_OBLIGATION_PASS:"+cs.ID)
	return b.String()
}

// assertionsSrc generates the body-assertion checks. bodyBytes/bodyStr are Go
// expressions yielding the response body ([]byte and string respectively).
func assertionsSrc(as []spec.BodyAssertion, bodyBytes, bodyStr string) string {
	var b strings.Builder
	needJSON := false
	for _, a := range as {
		switch a.Kind {
		case spec.AssertJSONKeyPresent, spec.AssertJSONKeyRFC3339, spec.AssertJSONKeyInTZ, spec.AssertJSONErrorPresent:
			needJSON = true
		}
	}
	if needJSON {
		fmt.Fprintf(&b, "\tvar body map[string]string\n\tif err := json.Unmarshal(%s, &body); err != nil {\n\t\tt.Fatalf(\"response is not JSON: %%v\", err)\n\t}\n", bodyBytes)
	}
	for _, a := range as {
		switch a.Kind {
		case spec.AssertJSONErrorPresent:
			b.WriteString("\tif strings.TrimSpace(body[\"error\"]) == \"\" {\n\t\tt.Fatal(\"response missing non-empty \\\"error\\\" key\")\n\t}\n")
		case spec.AssertJSONKeyPresent:
			fmt.Fprintf(&b, "\tif strings.TrimSpace(body[%q]) == \"\" {\n\t\tt.Fatalf(\"missing non-empty key %%q\", %q)\n\t}\n", a.Key, a.Key)
		case spec.AssertJSONKeyRFC3339:
			fmt.Fprintf(&b, "\tif _, err := time.Parse(time.RFC3339, body[%q]); err != nil {\n\t\tt.Fatalf(%q+\" not RFC3339: %%q\", body[%q])\n\t}\n", a.Key, a.Key, a.Key)
		case spec.AssertJSONKeyInTZ:
			b.WriteString(inTZSrc(a.Key, a.Value, "body["+fmt.Sprintf("%q", a.Key)+"]"))
		case spec.AssertBodyRFC3339:
			fmt.Fprintf(&b, "\tif _, err := time.Parse(time.RFC3339, strings.TrimSpace(%s)); err != nil {\n\t\tt.Fatalf(\"body not RFC3339: %%q\", %s)\n\t}\n", bodyStr, bodyStr)
		}
	}
	return b.String()
}

// inTZSrc asserts a timestamp value is RFC3339 AND sits at the offset of zone tz
// at that instant (DST-correct: the returned time's own offset must equal the
// zone's offset for that time).
func inTZSrc(key, tz, valExpr string) string {
	return fmt.Sprintf(`	{
		parsed, err := time.Parse(time.RFC3339, %s)
		if err != nil {
			t.Fatalf("%s not RFC3339: %%q", %s)
		}
		loc, err := time.LoadLocation(%q)
		if err != nil {
			t.Fatalf("bad zone %s: %%v", err)
		}
		_, want := parsed.In(loc).Zone()
		_, got := parsed.Zone()
		if got != want {
			t.Fatalf("%s offset = %%d, want zone %s (%%d)", got, want)
		}
	}
`, valExpr, key, valExpr, tz, tz, key, tz)
}

func queryString(q map[string]string) string {
	if len(q) == 0 {
		return ""
	}
	keys := make([]string, 0, len(q))
	for k := range q {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	vals := url.Values{}
	for _, k := range keys {
		vals.Set(k, q[k])
	}
	return "?" + vals.Encode()
}

// sanitize makes a case ID safe for a Go identifier suffix.
func sanitize(id string) string {
	var b strings.Builder
	for _, r := range id {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "x"
	}
	return b.String()
}

// legacyCorpus is the pre-requirements-model single-assertion corpus, preserved
// byte-for-byte so existing callers (no Cases) are unchanged.
func legacyCorpus(c Contract) string {
	if c.Route == "" {
		c.Route = "/" // neutral default, not a time-specific "/time"
	}
	var assert string
	if strings.ToLower(c.Format) == "text" {
		// Content-type only — the body is NOT assumed to be a timestamp.
		assert = `	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "text/plain") {
		t.Fatalf("content-type = %q, want text/plain", ct)
	}`
	} else {
		key, rfc3339 := c.JSONKey()
		assert = `	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "application/json") {
		t.Fatalf("content-type = %q, want application/json", ct)
	}`
		if key != "" { // a DECLARED key is checked; no time/key default
			assert += `
	var body map[string]string
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("response is not JSON: %v", err)
	}
	val, ok := body["` + key + `"]
	if !ok {
		t.Fatal("response missing required \"` + key + `\" field")
	}
	_ = val`
			if rfc3339 {
				assert += `
	if _, err := time.Parse(time.RFC3339, val); err != nil {
		t.Fatalf("\"` + key + `\" is not RFC3339: %q", val)
	}`
			}
		}
	}

	return fmt.Sprintf(`// Code generated by Orion proof/test-synthesis. DO NOT EDIT.
package main

import (
	"encoding/json"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

var _ = json.Unmarshal
var _ = strings.Contains
var _ = time.Parse // may be unused when no RFC3339 assertion is generated

// TestContractBehavior asserts the ResponseContract derived from the spec.
func TestContractBehavior(t *testing.T) {
	req := httptest.NewRequest("GET", %q, nil)
	w := httptest.NewRecorder()
	%s(w, req)
	if w.Code != 200 {
		t.Fatalf("status = %%d, want 200", w.Code)
	}
%s
}
`, c.Route, c.Entry(), assert)
}
