// Package testsynth authors behavioral tests FROM the spec — in the PROOF domain
// (or-60u, Trust invariant 1). The behavioral corpus is harness-owned and never
// authored by, or readable to, a generating agent. For the V2.0 Go HTTP
// time-service path, the corpus asserts the ResponseContract against the contract
// handler `handleTime` (a stable symbol of the generation contract).
//
// Manifesto: passing tests are not evidence of correctness unless the tests
// themselves come from the spec, independent of the code under test.
package testsynth

import (
	"fmt"
	"strings"
)

// Contract is the slice of the spec the behavioral corpus is synthesized from.
type Contract struct {
	Route    string
	Format   string // "json" | "text"
	TimeZone string
	// RequiredJSONKey generalizes the proof beyond the time-service (or-cfz): the
	// JSON response must contain this key. The empty default ("") means the V2.0
	// time contract — key "time" whose value must be an RFC3339 timestamp — so
	// every existing caller is unchanged. Any other key is asserted present only.
	RequiredJSONKey string
}

// JSONKey returns the required JSON key and whether its value must be RFC3339.
func (c Contract) JSONKey() (key string, rfc3339 bool) {
	if c.RequiredJSONKey == "" {
		return "time", true
	}
	return c.RequiredJSONKey, false
}

// SynthesizeBehavioral returns Go test source (a corpus file) asserting the
// ResponseContract. It is written by the proof domain, compiled with the
// artifact, and run independently.
func SynthesizeBehavioral(c Contract) string {
	if c.Route == "" {
		c.Route = "/time"
	}
	var assert string
	if strings.ToLower(c.Format) == "text" {
		assert = `	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "text/plain") {
		t.Fatalf("content-type = %q, want text/plain", ct)
	}
	if _, err := time.Parse(time.RFC3339, strings.TrimSpace(w.Body.String())); err != nil {
		t.Fatalf("body is not an RFC3339 time: %q", w.Body.String())
	}`
	} else {
		key, rfc3339 := c.JSONKey()
		assert = `	if ct := w.Header().Get("Content-Type"); !strings.Contains(ct, "application/json") {
		t.Fatalf("content-type = %q, want application/json", ct)
	}
	var body map[string]string
	if err := json.Unmarshal(w.Body.Bytes(), &body); err != nil {
		t.Fatalf("response is not JSON: %v", err)
	}
	val, ok := body["` + key + `"]
	if !ok {
		t.Fatal("response missing required \"` + key + `\" field")
	}
	_ = val`
		if rfc3339 {
			assert += `
	if _, err := time.Parse(time.RFC3339, val); err != nil {
		t.Fatalf("\"` + key + `\" is not RFC3339: %q", val)
	}`
		}
	}

	return fmt.Sprintf(`// Code generated by Orion proof/test-synthesis. DO NOT EDIT.
package main

import (
	"encoding/json"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

var _ = json.Unmarshal
var _ = strings.Contains

// TestContractBehavior asserts the ResponseContract derived from the spec.
func TestContractBehavior(t *testing.T) {
	req := httptest.NewRequest("GET", %q, nil)
	w := httptest.NewRecorder()
	handleTime(w, req)
	if w.Code != 200 {
		t.Fatalf("status = %%d, want 200", w.Code)
	}
%s
}
`, c.Route, assert)
}
