package testsynth

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/revelara-ai/orion/internal/orchestrator/spec"
)

// unitStepChecks is the SINGLE source of unit-step semantics (or-v9f.23 §4):
// both channels emit their step code through this function — behavioral wraps
// failures in t.Fatal, the empirical driver in a marker+exit — so what a step
// MEANS can never drift between them. fail renders a failure statement from a
// Go string-expression argument.
func unitStepChecks(cs spec.BehavioralCase, stepIdx int, fail func(msgExpr string) string) string {
	st := cs.Unit.Steps[stepIdx]
	var b strings.Builder
	b.WriteString("\t{\n")
	fmt.Fprintf(&b, "\t\tgot := %s\n", st.Call)
	if st.Want != "" {
		fmt.Fprintf(&b, "\t\twant := %s\n", st.Want)
		b.WriteString("\t\tif !reflect.DeepEqual(got, want) {\n")
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: got %%#v, want %%#v", got, want)`, stepIdx)) + "\n")
		b.WriteString("\t\t}\n")
	} else {
		b.WriteString("\t\terr, ok := any(got).(error)\n")
		b.WriteString("\t\tif !ok || err == nil {\n")
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: expected an error matching %%q, got %%#v", %q, got)`, stepIdx, st.WantErrRE)) + "\n")
		b.WriteString("\t\t}\n")
		fmt.Fprintf(&b, "\t\tif ok && err != nil && !regexp.MustCompile(%q).MatchString(err.Error()) {\n", st.WantErrRE)
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: error %%q does not match %%q", err.Error(), %q)`, stepIdx, st.WantErrRE)) + "\n")
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\t}\n")
	return b.String()
}

// SynthesizeUnitTests emits per-case IN-PACKAGE behavioral test files for unit
// cases: map of artifact-relative path → content. Cases narrowed to the
// empirical channel (restart cases) are skipped here — aggregateObligations'
// "passed in every mode that ran it" semantics handle the asymmetry. Package
// names are read from the artifact's own sources.
func SynthesizeUnitTests(cases []spec.BehavioralCase, artifactDir string) (map[string]string, error) {
	byPkg := map[string][]spec.BehavioralCase{}
	for _, cs := range cases {
		if cs.Kind != spec.KindUnit || cs.Unit == nil {
			continue
		}
		if len(cs.ModesApply) == 1 && cs.ModesApply[0] == "empirical" {
			continue // restart cases cross process boundaries; empirical-only
		}
		byPkg[cs.Unit.Pkg] = append(byPkg[cs.Unit.Pkg], cs)
	}
	out := map[string]string{}
	for pkg, pcs := range byPkg {
		pkgName, err := packageName(filepath.Join(artifactDir, pkg))
		if err != nil {
			return nil, fmt.Errorf("unit pkg %q: %w", pkg, err)
		}
		var b strings.Builder
		fmt.Fprintf(&b, "// Code generated by Orion proof/test-synthesis. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"fmt\"\n\t\"reflect\"\n\t\"regexp\"\n\t\"testing\"\n)\n\nvar (\n\t_ = reflect.DeepEqual\n\t_ = regexp.MustCompile\n\t_ = fmt.Sprintf\n)\n", pkgName)
		for _, cs := range pcs {
			fmt.Fprintf(&b, "\nfunc Test_obl_%s(t *testing.T) {\n", cs.ID)
			fmt.Fprintf(&b, "\tfmt.Println(%q)\n", "ORION_OBLIGATION_RUN:"+cs.ID)
			for i := range cs.Unit.Steps {
				b.WriteString(unitStepChecks(cs, i, func(msg string) string { return "t.Fatal(" + msg + ")" }))
			}
			fmt.Fprintf(&b, "\tfmt.Println(%q)\n}\n", "ORION_OBLIGATION_PASS:"+cs.ID)
		}
		out[filepath.Join(pkg, "orion_unit_obl_test.go")] = b.String()
	}
	return out, nil
}

// packageName reads the package clause of the first .go file in dir.
func packageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, e.Name()), nil, parser.PackageClauseOnly)
		if err != nil {
			return "", err
		}
		return f.Name.Name, nil
	}
	return "", fmt.Errorf("no Go sources in %s", dir)
}
