package testsynth

import (
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/revelara-ai/orion/internal/orchestrator/spec"
)

// unitStepChecks is the SINGLE source of unit-step semantics (or-v9f.23 §4):
// both channels emit their step code through this function — behavioral wraps
// failures in t.Fatal, the empirical driver in a marker+exit — so what a step
// MEANS can never drift between them. fail renders a failure statement from a
// Go string-expression argument.
func unitStepChecks(cs spec.BehavioralCase, stepIdx int, fail func(msgExpr string) string) string {
	st := cs.Unit.Steps[stepIdx]
	var b strings.Builder
	b.WriteString("\t{\n")
	fmt.Fprintf(&b, "\t\tgot := %s\n", st.Call)
	if st.Want != "" {
		fmt.Fprintf(&b, "\t\twant := %s\n", st.Want)
		b.WriteString("\t\tif !reflect.DeepEqual(got, want) {\n")
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: got %%#v, want %%#v", got, want)`, stepIdx)) + "\n")
		b.WriteString("\t\t}\n")
	} else {
		b.WriteString("\t\terr, ok := any(got).(error)\n")
		b.WriteString("\t\tif !ok || err == nil {\n")
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: expected an error matching %%q, got %%#v", %q, got)`, stepIdx, st.WantErrRE)) + "\n")
		b.WriteString("\t\t}\n")
		fmt.Fprintf(&b, "\t\tif ok && err != nil && !regexp.MustCompile(%q).MatchString(err.Error()) {\n", st.WantErrRE)
		b.WriteString("\t\t\t" + fail(fmt.Sprintf(`fmt.Sprintf("step %d: error %%q does not match %%q", err.Error(), %q)`, stepIdx, st.WantErrRE)) + "\n")
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\t}\n")
	return b.String()
}

// SynthesizeUnitTests emits per-case IN-PACKAGE behavioral test files for unit
// cases: map of artifact-relative path → content. Cases narrowed to the
// empirical channel (restart cases) are skipped here — aggregateObligations'
// "passed in every mode that ran it" semantics handle the asymmetry. Package
// names are read from the artifact's own sources.
func SynthesizeUnitTests(cases []spec.BehavioralCase, artifactDir string) (map[string]string, error) {
	byPkg := map[string][]spec.BehavioralCase{}
	for _, cs := range cases {
		if cs.Kind != spec.KindUnit || cs.Unit == nil {
			continue
		}
		if len(cs.ModesApply) == 1 && cs.ModesApply[0] == "empirical" {
			continue // restart cases cross process boundaries; empirical-only
		}
		byPkg[cs.Unit.Pkg] = append(byPkg[cs.Unit.Pkg], cs)
	}
	out := map[string]string{}
	for pkg, pcs := range byPkg {
		pkgName, err := packageName(filepath.Join(artifactDir, pkg))
		if err != nil {
			return nil, fmt.Errorf("unit pkg %q: %w", pkg, err)
		}
		var b strings.Builder
		fmt.Fprintf(&b, "// Code generated by Orion proof/test-synthesis. DO NOT EDIT.\npackage %s\n\nimport (\n\t\"fmt\"\n\t\"reflect\"\n\t\"regexp\"\n\t\"testing\"\n)\n\nvar (\n\t_ = reflect.DeepEqual\n\t_ = regexp.MustCompile\n\t_ = fmt.Sprintf\n)\n", pkgName)
		for _, cs := range pcs {
			fmt.Fprintf(&b, "\nfunc Test_obl_%s(t *testing.T) {\n", cs.ID)
			fmt.Fprintf(&b, "\tfmt.Println(%q)\n", "ORION_OBLIGATION_RUN:"+cs.ID)
			for i := range cs.Unit.Steps {
				b.WriteString(unitStepChecks(cs, i, func(msg string) string { return "t.Fatal(" + msg + ")" }))
			}
			fmt.Fprintf(&b, "\tfmt.Println(%q)\n}\n", "ORION_OBLIGATION_PASS:"+cs.ID)
		}
		out[filepath.Join(pkg, "orion_unit_obl_test.go")] = b.String()
	}
	return out, nil
}

// packageName reads the package clause of the first .go file in dir.
func packageName(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, e.Name()), nil, parser.PackageClauseOnly)
		if err != nil {
			return "", err
		}
		return f.Name.Name, nil
	}
	return "", fmt.Errorf("no Go sources in %s", dir)
}

// SynthesizeUnitDriver emits orion_unit_driver/main.go — the empirical channel
// for unit cases (or-v9f.23 §B2): a main package DOT-IMPORTING each case's
// package (package-scope call expressions work verbatim against the EXPORTED
// surface — the cross-module contract), executing one (caseID, segment) per
// invocation. Segments split at Restart steps; the harness re-execs the driver
// per segment in one scratch cwd, so crossing a segment IS a process boundary
// while on-disk state persists. Returns nil when no unit cases exist.
func SynthesizeUnitDriver(cases []spec.BehavioralCase, modulePath string) map[string]string {
	var unit []spec.BehavioralCase
	pkgs := map[string]bool{}
	for _, cs := range cases {
		if cs.Kind == spec.KindUnit && cs.Unit != nil {
			unit = append(unit, cs)
			pkgs[cs.Unit.Pkg] = true
		}
	}
	if len(unit) == 0 {
		return nil
	}
	var b strings.Builder
	b.WriteString("// Code generated by Orion proof/test-synthesis. DO NOT EDIT.\npackage main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n\t\"reflect\"\n\t\"regexp\"\n")
	for pkg := range pkgs {
		if pkg == "" {
			continue // root package is main for program artifacts; not importable — cases on it fail loud below
		}
		fmt.Fprintf(&b, "\t. %q\n", modulePath+"/"+filepath.ToSlash(pkg))
	}
	b.WriteString(")\n\nvar (\n\t_ = reflect.DeepEqual\n\t_ = regexp.MustCompile\n)\n\n")
	b.WriteString("func main() {\n\tif len(os.Args) != 3 {\n\t\tfmt.Fprintln(os.Stderr, \"usage: driver <caseID> <segment>\")\n\t\tos.Exit(2)\n\t}\n\tswitch os.Args[1] + \":\" + os.Args[2] {\n")
	fail := func(msg string) string {
		return `fmt.Fprintln(os.Stderr, ` + msg + `); os.Exit(1)`
	}
	for _, cs := range unit {
		if cs.Unit.Pkg == "" {
			fmt.Fprintf(&b, "\tcase %q:\n\t\tfmt.Fprintln(os.Stderr, \"unit case %s targets the root package, which is not importable — move the behavior into a named package\")\n\t\tos.Exit(1)\n", cs.ID+":0", cs.ID)
			continue
		}
		seg := 0
		fmt.Fprintf(&b, "\tcase %q:\n", cs.ID+":0")
		for i := range cs.Unit.Steps {
			if cs.Unit.Steps[i].Restart {
				seg++
				fmt.Fprintf(&b, "\tcase %q:\n", fmt.Sprintf("%s:%d", cs.ID, seg))
			}
			b.WriteString(unitStepChecks(cs, i, fail))
		}
	}
	b.WriteString("\tdefault:\n\t\tfmt.Fprintln(os.Stderr, \"unknown case/segment\")\n\t\tos.Exit(2)\n\t}\n}\n")
	return map[string]string{"orion_unit_driver/main.go": b.String()}
}

// UnitSegments counts a case's process segments (1 + restart steps).
func UnitSegments(cs spec.BehavioralCase) int {
	n := 1
	if cs.Kind != spec.KindUnit || cs.Unit == nil {
		return 0
	}
	for _, st := range cs.Unit.Steps {
		if st.Restart {
			n++
		}
	}
	return n
}
