package sandbox

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"text/template"

	"github.com/revelara-ai/orion/internal/actuation"
	"github.com/revelara-ai/orion/internal/contextstore"
	"github.com/revelara-ai/orion/internal/orchestrator/spec"
)

// GenSpec is the slice of the executable spec the Go-service generator needs.
type GenSpec struct {
	Module   string // go module path (e.g. "orion-generated/timeservice")
	Route    string // e.g. "/time"
	Port     int    // e.g. 8080
	Format   string // "json" | "text"
	TimeZone string // "UTC" | IANA name
	// Cases are the behavioral cases the generated program must satisfy (the
	// contract). The native LLM generator builds arbitrary code to these; the
	// deterministic fixture ignores them (it only knows the canonical time service).
	Cases []spec.BehavioralCase
}

// GeneratedArtifact describes a written file.
type GeneratedArtifact struct {
	Path        string
	ContentHash string
}

// GenerateFixtureService writes a real, compilable Go HTTP time-service into dir
// (the agent's worktree), conforming to the ResponseContract. The generated
// service carries reliability primitives (server timeouts, graceful shutdown) —
// Orion eats its own dog food. Returns the main.go artifact descriptor.
func GenerateFixtureService(dir string, gs GenSpec) (GeneratedArtifact, error) {
	if gs.Module == "" {
		gs.Module = "orion-generated/timeservice"
	}
	if gs.Route == "" {
		gs.Route = "/time"
	}
	if gs.Port == 0 {
		gs.Port = 8080
	}
	if gs.TimeZone == "" {
		gs.TimeZone = "UTC"
	}

	gomod := fmt.Sprintf("module %s\n\ngo 1.25\n", gs.Module)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o644); err != nil {
		return GeneratedArtifact{}, fmt.Errorf("write go.mod: %w", err)
	}

	var buf []byte
	{
		tmpl := template.Must(template.New("main").Parse(mainTemplate))
		w := &bytesBuffer{}
		if err := tmpl.Execute(w, gs); err != nil {
			return GeneratedArtifact{}, fmt.Errorf("render template: %w", err)
		}
		buf = w.b
	}
	mainPath := filepath.Join(dir, "main.go")
	if err := os.WriteFile(mainPath, buf, 0o644); err != nil {
		return GeneratedArtifact{}, fmt.Errorf("write main.go: %w", err)
	}
	sum := sha256.Sum256(buf)
	return GeneratedArtifact{Path: mainPath, ContentHash: hex.EncodeToString(sum[:])}, nil
}

// PersistArtifact records a generated artifact in the Context Store (artifacts
// entity), tying it to the producing task.
func PersistArtifact(ctx context.Context, store *contextstore.Store, taskID string, a GeneratedArtifact) (string, error) {
	var id string
	err := store.WithTx(ctx, func(tx *contextstore.Tx) error {
		var e error
		id, e = tx.Artifacts().Create(ctx, taskID, "code", a.Path, a.ContentHash)
		return e
	})
	return id, err
}

type bytesBuffer struct{ b []byte }

func (w *bytesBuffer) Write(p []byte) (int, error) { w.b = append(w.b, p...); return len(p), nil }

// mainTemplate is a real net/http service with timeouts + graceful shutdown.
const mainTemplate = `// Code generated by Orion. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"log"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"time"
)

var requestsServed atomic.Int64

// instrument adds structured logging, latency metrics, and request-id trace
// propagation around a handler (operability: the 3 a.m. test).
func instrument(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		rid := r.Header.Get("X-Request-ID")
		if rid == "" {
			rid = start.Format("20060102T150405.000000000")
		}
		w.Header().Set("X-Request-ID", rid)
		next.ServeHTTP(w, r)
		slog.Info("request",
			"method", r.Method, "path", r.URL.Path, "request_id", rid,
			"latency_ms", time.Since(start).Milliseconds(),
			"requests_served", requestsServed.Add(1))
	})
}

func location() *time.Location {
	{{if eq .TimeZone "UTC"}}return time.UTC{{else}}loc, err := time.LoadLocation({{printf "%q" .TimeZone}})
	if err != nil {
		return time.UTC
	}
	return loc{{end}}
}

func handleTime(w http.ResponseWriter, r *http.Request) {
	now := time.Now().In(location())
{{if eq .Format "text"}}	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	_, _ = w.Write([]byte(now.Format(time.RFC3339)))
{{else}}	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]string{"time": now.Format(time.RFC3339)})
{{end}}}

func main() {
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stderr, nil)))
	mux := http.NewServeMux()
	mux.Handle({{printf "%q" .Route}}, instrument(http.HandlerFunc(handleTime)))

	addr := ":{{.Port}}"
	if p := os.Getenv("PORT"); p != "" {
		addr = ":" + p
	}
	srv := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server error: %v", err)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	<-stop

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = srv.Shutdown(ctx)
}
`

// PrepareArtifact writes the given files into dir, or — under dryRun — predicts
// the effect and blast radius WITHOUT mutating the filesystem (or-nwb dry-run
// contract). The reversibility gate calls this with dryRun=true first.
func PrepareArtifact(dir string, files map[string]string, dryRun bool) (actuation.Prediction, error) {
	if dryRun {
		return actuation.Prediction{
			Tool:        "sandbox.write",
			Effect:      fmt.Sprintf("would write %d file(s)", len(files)),
			BlastRadius: "task worktree: " + dir,
			Mutated:     false,
		}, nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return actuation.Prediction{}, err
	}
	for name, content := range files {
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return actuation.Prediction{}, err
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			return actuation.Prediction{}, err
		}
	}
	return actuation.Prediction{
		Tool:        "sandbox.write",
		Effect:      fmt.Sprintf("wrote %d file(s)", len(files)),
		BlastRadius: "task worktree: " + dir,
		Mutated:     true,
	}, nil
}

// ArtifactFromDir builds a GeneratedArtifact from a directory the generator wrote
// (e.g. a spawned agent authoring via the ACP fs seam): a stable content hash
// over all files + a representative path. Used when generation is not the
// deterministic fixture.
func ArtifactFromDir(dir string) (GeneratedArtifact, error) {
	var files []string
	if err := filepath.WalkDir(dir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			files = append(files, p)
		}
		return nil
	}); err != nil {
		return GeneratedArtifact{}, err
	}
	if len(files) == 0 {
		return GeneratedArtifact{}, fmt.Errorf("artifact dir %s is empty", dir)
	}
	sort.Strings(files)
	h := sha256.New()
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return GeneratedArtifact{}, err
		}
		rel, _ := filepath.Rel(dir, f)
		h.Write([]byte(rel))
		h.Write(b)
	}
	path := filepath.Join(dir, "main.go")
	if _, err := os.Stat(path); err != nil {
		path = files[0]
	}
	return GeneratedArtifact{Path: path, ContentHash: hex.EncodeToString(h.Sum(nil))}, nil
}
