package sandbox

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/revelara-ai/orion/internal/contextstore"
)

// GenSpec is the slice of the executable spec the Go-service generator needs.
type GenSpec struct {
	Module   string // go module path (e.g. "orion-generated/timeservice")
	Route    string // e.g. "/time"
	Port     int    // e.g. 8080
	Format   string // "json" | "text"
	TimeZone string // "UTC" | IANA name
}

// GeneratedArtifact describes a written file.
type GeneratedArtifact struct {
	Path        string
	ContentHash string
}

// GenerateGoTimeService writes a real, compilable Go HTTP time-service into dir
// (the agent's worktree), conforming to the ResponseContract. The generated
// service carries reliability primitives (server timeouts, graceful shutdown) —
// Orion eats its own dog food. Returns the main.go artifact descriptor.
func GenerateGoTimeService(dir string, gs GenSpec) (GeneratedArtifact, error) {
	if gs.Module == "" {
		gs.Module = "orion-generated/timeservice"
	}
	if gs.Route == "" {
		gs.Route = "/time"
	}
	if gs.Port == 0 {
		gs.Port = 8080
	}
	if gs.TimeZone == "" {
		gs.TimeZone = "UTC"
	}

	gomod := fmt.Sprintf("module %s\n\ngo 1.25\n", gs.Module)
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(gomod), 0o644); err != nil {
		return GeneratedArtifact{}, fmt.Errorf("write go.mod: %w", err)
	}

	var buf []byte
	{
		tmpl := template.Must(template.New("main").Parse(mainTemplate))
		w := &bytesBuffer{}
		if err := tmpl.Execute(w, gs); err != nil {
			return GeneratedArtifact{}, fmt.Errorf("render template: %w", err)
		}
		buf = w.b
	}
	mainPath := filepath.Join(dir, "main.go")
	if err := os.WriteFile(mainPath, buf, 0o644); err != nil {
		return GeneratedArtifact{}, fmt.Errorf("write main.go: %w", err)
	}
	sum := sha256.Sum256(buf)
	return GeneratedArtifact{Path: mainPath, ContentHash: hex.EncodeToString(sum[:])}, nil
}

// PersistArtifact records a generated artifact in the Context Store (artifacts
// entity), tying it to the producing task.
func PersistArtifact(ctx context.Context, store *contextstore.Store, taskID string, a GeneratedArtifact) (string, error) {
	var id string
	err := store.WithTx(ctx, func(tx *contextstore.Tx) error {
		var e error
		id, e = tx.Artifacts().Create(ctx, taskID, "code", a.Path, a.ContentHash)
		return e
	})
	return id, err
}

type bytesBuffer struct{ b []byte }

func (w *bytesBuffer) Write(p []byte) (int, error) { w.b = append(w.b, p...); return len(p), nil }

// mainTemplate is a real net/http service with timeouts + graceful shutdown.
const mainTemplate = `// Code generated by Orion. DO NOT EDIT.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"
)

func location() *time.Location {
	{{if eq .TimeZone "UTC"}}return time.UTC{{else}}loc, err := time.LoadLocation({{printf "%q" .TimeZone}})
	if err != nil {
		return time.UTC
	}
	return loc{{end}}
}

func handleTime(w http.ResponseWriter, r *http.Request) {
	now := time.Now().In(location())
{{if eq .Format "text"}}	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	_, _ = w.Write([]byte(now.Format(time.RFC3339)))
{{else}}	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]string{"time": now.Format(time.RFC3339)})
{{end}}}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc({{printf "%q" .Route}}, handleTime)

	addr := ":{{.Port}}"
	if p := os.Getenv("PORT"); p != "" {
		addr = ":" + p
	}
	srv := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       60 * time.Second,
	}

	go func() {
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatalf("server error: %v", err)
		}
	}()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGINT, syscall.SIGTERM)
	<-stop

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = srv.Shutdown(ctx)
}
`
