package delivery

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/revelara-ai/orion/internal/orchestrator/spec"
	"github.com/revelara-ai/orion/internal/proof/hazard/stpa"
)

// Generated investigation analyzer (or-nkcf, DrP pattern — Somani et al.,
// arXiv 2512.04250): every proven deliverable ships an EXECUTABLE triage
// artifact next to the prose runbook, because prose playbooks rot and
// executable ones do not. Reuse, not invention: the contract's behavioral
// cases are the data-access layer (they already know how to interrogate the
// service), the runbook's incident steps become proposed actions, the STPA
// UCAs become failure hypotheses. The analyzer PROPOSES findings for a human
// to validate (DrP: assist, not autonomous mitigation) — structured JSON on
// stdout, exit 2 when findings exist, 0 clean, 1 analyzer error.
//
// The emitted program is a standalone stdlib-only main package
// (cmd/analyze/main.go in the delivered tree): a fixed interpreter over an
// embedded check table, so generation is deterministic data, not free-form
// code.

// analyzerCheck is one embedded probe: request + expectations, the same
// vocabulary the empirical proof drove.
type analyzerCheck struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Method      string            `json:"method"`
	Path        string            `json:"path"`
	Query       map[string]string `json:"query,omitempty"`
	Body        string            `json:"body,omitempty"`
	Status      int               `json:"status"`
	ContentType string            `json:"content_type,omitempty"`
	Assertions  []analyzerAssert  `json:"assertions,omitempty"`
}

type analyzerAssert struct {
	Kind  string `json:"kind"`
	Key   string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}

type analyzerManifest struct {
	SpecHash        string          `json:"spec_hash"`
	Intent          string          `json:"intent"`
	DefaultBase     string          `json:"default_base"`
	Checks          []analyzerCheck `json:"checks"`
	Hypotheses      []string        `json:"hypotheses"`       // STPA UCAs — where this service is KNOWN to be able to fail
	ProposedActions []string        `json:"proposed_actions"` // runbook incident steps, codified
}

// GenerateAnalyzer renders the analyzer source for a delivered service.
// Deterministic: same spec/model/runbook → byte-identical source.
func GenerateAnalyzer(es spec.ExecutableSpec, model stpa.Model, rb Runbook) string {
	m := analyzerManifest{
		SpecHash:    es.Hash,
		Intent:      es.Intent,
		DefaultBase: fmt.Sprintf("http://localhost:%d", es.ResponseContract.Port),
	}
	for _, c := range es.ResponseContract.Cases {
		if c.Kind != spec.KindHTTP && c.Kind != "" {
			continue // exec/unit/file cases don't probe a RUNNING service
		}
		chk := analyzerCheck{
			ID:          c.ID,
			Method:      c.Request.Method,
			Path:        c.Request.Path,
			Query:       c.Request.Query,
			Body:        c.Request.Body,
			Status:      c.Expect.Status,
			ContentType: c.Expect.ContentType,
		}
		chk.Name = strings.TrimSpace(c.Request.Method + " " + c.Request.Path)
		for _, a := range c.Expect.Assertions {
			chk.Assertions = append(chk.Assertions, analyzerAssert{Kind: string(a.Kind), Key: a.Key, Value: a.Value})
		}
		m.Checks = append(m.Checks, chk)
	}
	if len(m.Checks) == 0 && es.ResponseContract.Route != "" {
		// Legacy single-route contract: at minimum, the health probe.
		m.Checks = append(m.Checks, analyzerCheck{
			ID: "health", Name: "GET " + es.ResponseContract.Route + " answers 200",
			Method: "GET", Path: es.ResponseContract.Route, Status: 200,
		})
	}
	ucas := append([]stpa.UCA(nil), model.UCAs...)
	sort.Slice(ucas, func(i, j int) bool { return ucas[i].ID < ucas[j].ID })
	for _, u := range ucas {
		m.Hypotheses = append(m.Hypotheses, fmt.Sprintf("%s (%s): %s", u.ID, u.Type, u.Hazard))
	}
	for _, line := range strings.Split(rb.Sections["incident_response"], "\n") {
		if line = strings.TrimSpace(line); line != "" {
			m.ProposedActions = append(m.ProposedActions, line)
		}
	}
	mj, _ := json.MarshalIndent(m, "", "  ")
	// %q-quote the manifest into the source so backticks/quotes in spec text
	// can never break the emitted program.
	return fmt.Sprintf(analyzerTemplate, fmt.Sprintf("%q", string(mj)))
}

// analyzerTemplate is the fixed interpreter. One %s hole: the quoted manifest.
const analyzerTemplate = `// Code generated by Orion (investigation analyzer, DrP pattern). DO NOT EDIT.
// Regenerate by re-running the Orion delivery for this service — analyzers
// rot when edited by hand (DrP §4.4); this one is rebuilt from the proven
// contract on every delivery.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

var manifestJSON = %s

type check struct {
	ID          string            ` + "`json:\"id\"`" + `
	Name        string            ` + "`json:\"name\"`" + `
	Method      string            ` + "`json:\"method\"`" + `
	Path        string            ` + "`json:\"path\"`" + `
	Query       map[string]string ` + "`json:\"query,omitempty\"`" + `
	Body        string            ` + "`json:\"body,omitempty\"`" + `
	Status      int               ` + "`json:\"status\"`" + `
	ContentType string            ` + "`json:\"content_type,omitempty\"`" + `
	Assertions  []assert          ` + "`json:\"assertions,omitempty\"`" + `
}

type assert struct {
	Kind  string ` + "`json:\"kind\"`" + `
	Key   string ` + "`json:\"key,omitempty\"`" + `
	Value string ` + "`json:\"value,omitempty\"`" + `
}

type manifest struct {
	SpecHash        string   ` + "`json:\"spec_hash\"`" + `
	Intent          string   ` + "`json:\"intent\"`" + `
	DefaultBase     string   ` + "`json:\"default_base\"`" + `
	Checks          []check  ` + "`json:\"checks\"`" + `
	Hypotheses      []string ` + "`json:\"hypotheses\"`" + `
	ProposedActions []string ` + "`json:\"proposed_actions\"`" + `
}

type result struct {
	ID     string ` + "`json:\"id\"`" + `
	Name   string ` + "`json:\"name\"`" + `
	OK     bool   ` + "`json:\"ok\"`" + `
	Detail string ` + "`json:\"detail,omitempty\"`" + `
}

type report struct {
	Analyzer        string   ` + "`json:\"analyzer\"`" + `
	SpecHash        string   ` + "`json:\"spec_hash\"`" + `
	Intent          string   ` + "`json:\"intent\"`" + `
	Target          string   ` + "`json:\"target\"`" + `
	Checks          []result ` + "`json:\"checks\"`" + `
	Findings        []string ` + "`json:\"findings\"`" + `
	Hypotheses      []string ` + "`json:\"hypotheses,omitempty\"`" + `
	ProposedActions []string ` + "`json:\"proposed_actions,omitempty\"`" + `
	Note            string   ` + "`json:\"note\"`" + `
}

func main() {
	var m manifest
	if err := json.Unmarshal([]byte(manifestJSON), &m); err != nil {
		fmt.Fprintln(os.Stderr, "analyzer: bad embedded manifest:", err)
		os.Exit(1)
	}
	base := flag.String("base", m.DefaultBase, "service base URL to investigate")
	flag.Parse()

	client := &http.Client{Timeout: 5 * time.Second}
	rep := report{
		Analyzer: "orion-investigation", SpecHash: m.SpecHash, Intent: m.Intent,
		Target: *base,
		Note:   "proposed findings — a human validates before acting (assist, not autonomous mitigation)",
	}
	for _, c := range m.Checks {
		ok, detail := run(client, *base, c)
		rep.Checks = append(rep.Checks, result{ID: c.ID, Name: c.Name, OK: ok, Detail: detail})
		if !ok {
			rep.Findings = append(rep.Findings, c.Name+": "+detail)
		}
	}
	if len(rep.Findings) > 0 {
		rep.Hypotheses = m.Hypotheses
		rep.ProposedActions = m.ProposedActions
	}
	out, _ := json.MarshalIndent(rep, "", "  ")
	fmt.Println(string(out))
	if len(rep.Findings) > 0 {
		os.Exit(2)
	}
}

func run(client *http.Client, base string, c check) (bool, string) {
	u := base + c.Path
	if len(c.Query) > 0 {
		q := url.Values{}
		for k, v := range c.Query {
			q.Set(k, v)
		}
		u += "?" + q.Encode()
	}
	method := c.Method
	if method == "" {
		method = "GET"
	}
	req, err := http.NewRequest(method, u, strings.NewReader(c.Body))
	if err != nil {
		return false, "request build failed: " + err.Error()
	}
	resp, err := client.Do(req)
	if err != nil {
		return false, "service unreachable: " + err.Error()
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if c.Status != 0 && resp.StatusCode != c.Status {
		return false, fmt.Sprintf("status %%d, expected %%d", resp.StatusCode, c.Status)
	}
	if c.ContentType != "" && !strings.Contains(resp.Header.Get("Content-Type"), c.ContentType) {
		return false, "content-type " + resp.Header.Get("Content-Type") + ", expected " + c.ContentType
	}
	for _, a := range c.Assertions {
		if ok, detail := assertOne(a, body); !ok {
			return false, detail
		}
	}
	return true, ""
}

func assertOne(a assert, body []byte) (bool, string) {
	var doc map[string]any
	jsonErr := json.Unmarshal(body, &doc)
	get := func(key string) (string, bool) {
		if jsonErr != nil {
			return "", false
		}
		v, ok := doc[key]
		if !ok {
			return "", false
		}
		s, isStr := v.(string)
		if !isStr {
			return fmt.Sprint(v), true
		}
		return s, true
	}
	switch a.Kind {
	case "json_key_present":
		if _, ok := get(a.Key); !ok {
			return false, "json key " + a.Key + " missing"
		}
	case "json_error_present":
		if _, ok := get("error"); !ok {
			return false, "json error field missing"
		}
	case "json_key_rfc3339":
		s, ok := get(a.Key)
		if !ok {
			return false, "json key " + a.Key + " missing"
		}
		if _, err := time.Parse(time.RFC3339, s); err != nil {
			return false, a.Key + " is not RFC3339: " + s
		}
	case "json_key_in_tz":
		s, ok := get(a.Key)
		if !ok {
			return false, "json key " + a.Key + " missing"
		}
		ts, err := time.Parse(time.RFC3339, s)
		if err != nil {
			return false, a.Key + " is not RFC3339: " + s
		}
		loc, err := time.LoadLocation(a.Value)
		if err != nil {
			return false, "unknown tz " + a.Value
		}
		_, wantOff := time.Now().In(loc).Zone()
		_, gotOff := ts.Zone()
		if wantOff != gotOff {
			return false, fmt.Sprintf("%%s offset %%d, expected tz %%s offset %%d", a.Key, gotOff, a.Value, wantOff)
		}
	case "body_rfc3339":
		if _, err := time.Parse(time.RFC3339, strings.TrimSpace(string(body))); err != nil {
			return false, "body is not RFC3339"
		}
	default:
		if a.Kind != "" {
			return false, "unknown assertion kind " + a.Kind
		}
	}
	return true, ""
}
`
