package conductor

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/revelara-ai/orion/internal/brownfield"
	"github.com/revelara-ai/orion/internal/contextstore"
	"github.com/revelara-ai/orion/internal/llm"
	"github.com/revelara-ai/orion/internal/worktree"
)

// ChangeResult is the outcome of a brownfield change-proof.
type ChangeResult struct {
	Branch       string
	Path         string // the worktree the change lives in
	Regression   brownfield.RegressionResult
	FilesChanged []string
	Committed    bool
	Reason       string // why not committed, if applicable
}

// ChangeAndProve runs the brownfield change loop end-to-end: it creates a WORKTREE off
// HEAD (the developer's working tree is never touched), has the diff generator edit it
// to the intent, then proves the change PRESERVED existing behavior via the regression
// gate (green-before → green-after). On success the change is committed on the worktree
// branch for review/PR; on a regression it is left uncommitted with the reason.
//
// This is the "do no harm + deliver" spine of brownfield. The NEW-behavior proof
// (harness-authored obligations targeting the changed surface) and STAMP-baseline
// preservation are the next rigor layers on top of this regression-gated loop.
func ChangeAndProve(ctx context.Context, repoRoot string, store *contextstore.Store, provider llm.Provider, intent string) (ChangeResult, error) {
	m := brownfield.ScanRepoMap(repoRoot)

	mgr := worktree.New(repoRoot, store)
	issueID := "orion-change-" + slugFromIntent(intent)
	wt, err := mgr.Create(ctx, issueID, "HEAD")
	if err != nil {
		if wt, err = mgr.CreateResume(ctx, issueID, issueID); err != nil {
			return ChangeResult{}, fmt.Errorf("worktree for change: %w", err)
		}
	}
	res := ChangeResult{Branch: wt.Branch, Path: wt.Path}

	// Regression gate: green-before (worktree == HEAD) → the generator edits the
	// worktree → green-after. The generator IS the change being applied. Opt-in
	// ORION_REGRESSION_SCOPE=blast scopes the gate to the changed packages + their
	// blast radius (fast on big repos, e.g. Orion-on-Orion); default is the full suite
	// (sound against out-of-import-graph regressions). See or-3p5.5.
	apply := func() error {
		return DiffGenerator(ctx, provider, wt.Path, intent, m.Digest())
	}
	var reg brownfield.RegressionResult
	if os.Getenv("ORION_REGRESSION_SCOPE") == "blast" {
		reg, err = brownfield.RegressionGateScoped(ctx, wt.Path, m, apply)
	} else {
		reg, err = brownfield.RegressionGate(ctx, wt.Path, apply)
	}
	if err != nil {
		return res, fmt.Errorf("regression gate: %w", err)
	}
	res.Regression = reg
	res.FilesChanged = changedFiles(ctx, wt.Path)

	if !reg.Held {
		res.Reason = reg.Reason
		return res, nil // change generated but it did not preserve existing behavior — not committed
	}

	if _, err := gitIn(ctx, wt.Path, "add", "-A"); err != nil {
		return res, err
	}
	if _, err := gitIn(ctx, wt.Path,
		"-c", "user.name=Orion", "-c", "user.email=orion@revelara.ai", "-c", "commit.gpgsign=false",
		"commit", "--no-verify", "-m", changeMessage(intent)); err != nil {
		return res, err
	}
	res.Committed = true
	return res, nil
}

// changedFiles returns the paths the change touched in the worktree (git status).
func changedFiles(ctx context.Context, dir string) []string {
	out, err := gitIn(ctx, dir, "status", "--porcelain")
	if err != nil || strings.TrimSpace(out) == "" {
		return nil
	}
	var files []string
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if len(line) > 3 {
			files = append(files, strings.TrimSpace(line[3:]))
		}
	}
	return files
}

func changeMessage(intent string) string {
	return fmt.Sprintf("orion: %s (regression-proven)\n\nGenerated by Orion for an existing repo; the existing test suite stayed green across the change.\n", oneLine(intent))
}

// slugFromIntent makes a short, filesystem/branch-safe slug from a change intent.
func slugFromIntent(intent string) string {
	var b strings.Builder
	for _, c := range strings.ToLower(strings.TrimSpace(intent)) {
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			b.WriteRune(c)
		case c == ' ' || c == '-' || c == '_':
			b.WriteByte('-')
		}
		if b.Len() >= 40 {
			break
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		s = "change"
	}
	return s
}
