// Package llm provides a thin Vertex AI / Gemini client wrapper for orion.
//
// Designed as a slim mirror of polaris's internal/llm pattern (same SDK,
// same auth chain), without polaris-specific concerns (circuit breaker,
// rate limiter, usage repo, OTel tracing). Those land in dedicated
// reliability epics; for v1 architectural inference and patch synthesis
// we just need a Generate(ctx, req) primitive plus an interface for
// mocking.
//
// Auth chain: Vertex AI backend with Application Default Credentials.
// Set GOOGLE_CLOUD_PROJECT + GOOGLE_CLOUD_LOCATION (and ensure
// `gcloud auth application-default login` has run) and the SDK picks
// up credentials transparently.
package llm

import "errors"

// Sentinel errors for callers to errors.Is against.
var (
	// ErrAuthMissing: required auth env vars (GOOGLE_CLOUD_PROJECT and
	// GOOGLE_CLOUD_LOCATION) are not both set.
	ErrAuthMissing = errors.New("llm: vertex auth not configured")

	// ErrInvalidConfig: a required config field other than auth is unset
	// (e.g., Model name).
	ErrInvalidConfig = errors.New("llm: invalid config")

	// ErrGenerationFailed: the underlying generation call failed (network,
	// quota, server). Wrapped error carries the SDK-level cause.
	ErrGenerationFailed = errors.New("llm: generation failed")

	// ErrEmptyResponse: the SDK returned a successful response but with no
	// candidate text. Surfaced separately so callers can choose to retry.
	ErrEmptyResponse = errors.New("llm: empty response")
)

// GenerateRequest is the per-call input.
type GenerateRequest struct {
	// System is an optional system-instruction string. Empty means no
	// system instruction.
	System string

	// User is the user/turn text. Required.
	User string

	// MaxTokens caps generation length. 0 means use the SDK default.
	MaxTokens int

	// Temperature is the generation temperature. Negative means use the
	// SDK default; 0 means greedy.
	Temperature float32
}

// GenerateResponse is the per-call output.
type GenerateResponse struct {
	// Text is the concatenated text of the first candidate.
	Text string

	// Model is the model identifier the response was generated by.
	Model string

	// FinishReason is the SDK-reported finish reason ("STOP", "MAX_TOKENS",
	// "SAFETY", etc.). Empty if the SDK didn't return one.
	FinishReason string

	// TokensIn / TokensOut are token counts when reported by the SDK.
	TokensIn  int
	TokensOut int
}
